### ISSUE TITLE
Ability to set psx clock, speed hack and switch to gpu_peops

### ISSUE THREAD

**Issue by thelostabbey** [screemerpl/cbleemsync#101]
I am having some minor slowdown when playing Legend of Legaia during battle sequences (heard it affects other games like Legend of Dragoon too).  I heard the old sPSXe plugins like  p.e.ops gpu and p.e.ops sound files played these sequences correctly. Can this be looked into?

**Comment by screemerpl** [comment]
The new 0.6 build will have brand new build of PCSXe... autobleem uses mostly "build in neon" plugin as it is most stable at the moment. It is possible that we can add a switch to  select peops gpu for certain games, but this probably will not be ready for 0.6.0 release ... maybe we can do it for 0.6.1 hotfix ... (funny fact ... internal version of Metal Gear Solid uses peops gpu plugin already). Also you can try to change clock rate using pcsx.cfg file inside game folder.

**Comment by thelostabbey** [comment]
sounds great! can't wait to try 0.6.
