### ISSUE TITLE
controller input lag

### ISSUE THREAD

**Issue by AlexanderVarela** [screemerpl/cbleemsync#105]
I have been testing a few games and there is a lag between the controller and the game, making the games hard to play (some games more lag than others). in this case will be Jackie Chan Stunt Master.

**Comment by screemerpl** [comment]
This is i think a general lag of HDMI plus the pcsx emulator itself...some games were designed to be played on crt monitors (as there were no LCD at that time). I actually have this game on my psc and the lag on my HDMI gaming monitor in game mode is totally acceptable ... We already had a conversation in the team about this some day and realized that ..psc is finally just an emulator, not a real device connected to a crt

**Comment by screemerpl** [comment]
Closing as nothing we can do with it at the moment
