### ISSUE TITLE
128gb flashdrive not working

### ISSUE THREAD

**Issue by toddw183** [screemerpl/cbleemsync#109]
Bought a new PSC at Best Buy. Had been marked down to $39.99. Setup a 128gb flash drive. Flash drive works in older PSC but when put in the new one I get nothing. 32gb works in new one. But not the 128gb.

**Comment by TheGreenGoblin** [comment]
Are you using a powered USB hub? Is the 128GB drive formatted in FAT32 and/or have you installed the Bleemsysnc 1.0.0 payload onto your new PSC?

**Comment by toddw183** [comment]
No powerhub
Yes it’s FAT32 (it works fine on old PSC)
Yes Bleemsync is installed

**Comment by TheGreenGoblin** [comment]
Did the old PSC have that hardware mod to bypass the USB ports' 100ma power limitation? If the new one doesn't have that, a powered USB hub will probably solve all your problems. The $19.99 Insignia one from Best Buy is a good low cost option.

**Comment by toddw183** [comment]
Nope didn’t do any hard modifications to the old one.

**Comment by AutoBleemFan** [comment]
This worked for my with my 128GB drive: Don't push the usb device to far into the usb port of PCS otherwise auto bleem will not recognize it (not always). Just push it slightly in and it will work everytime.

**Comment by screemerpl** [comment]
Nothing to do for us :) Closing.
