### ISSUE TITLE
Global and per game config are not recognised

### ISSUE THREAD

**Issue by francescoaracu** [screemerpl/cbleemsync#113]
After saving either global and per game configs, on the next starting of the game they won't be recognized. The files are properly stored in the game subfolder under /Games/!SaveState/.

**Comment by screemerpl** [comment]
Yes they are not as the only config PSC version of PCSX reads is the one inside game folder. This is not going to be fixed as this is the way pcsx on this console works (Sony implemented that this way).... just copy your changed config to game folder.
