### ISSUE TITLE
PCSX Menu options not saved - AutoBleem 0.6.0 Beta 1

### ISSUE THREAD

**Issue by Rallyace** [screemerpl/cbleemsync#115]
I went into the PCSX Menu to change the option for Tekken 3 from "Auto" to "NTSC" as it defaults to PAL. I have tried "save cfg for loaded game" and also "save golbal cfg" but it always reverts to Auto and therefore PAL.

I have also tried copying / editing the cfg files to change the region to 1, but it still starts on PAL region!!!

**Comment by screemerpl** [comment]
This is issue with PCSX, not the AutoBleem  .... the options to save configuration created by Sony in hidden menu DO NOT WORK, and will not work correctly (even with original games !!!) - do not use those options. The only cfg file you may edit is the one inside game folder.

**Comment by Rallyace** [comment]
How do you edit the cfg file inside the game folder for the 20 pre installed games?



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by screemerpl** [comment]
Preinstalled games have it's own configuration prepared by Sony and that is what AutoBleem 0.6 beta 2 (not released in public - will be released soon) use. You will be able to edit the pcsx.cfg inside Games/!SaveStates/NUMBER for those games, but as far we found those games have some hacks directly inside PCSX code, so PCSX ignores some of the settings (for example you can not change gpu plugin in MGS, value is just ignored and replaced with hard coded one).
