### ISSUE TITLE
Some Savestates not working

### ISSUE THREAD

**Issue by StephenFlagg** [screemerpl/cbleemsync#116]
Savestates for Final Fantasy IX and Chrono Cross aren't working correctly.  After loading the savestate, the game works until you try to load a new screen, and the game either freezes or knocks you back to the games menu.
Savestates for every other game I've played seem to work fine.

**Comment by screemerpl** [comment]
Yes we know - its issue in 0.6 beta ... The problem is with multidisc games. I am working to fix it for beta2/release candidate version.

**Comment by StephenFlagg** [comment]
Thanks!
