### ISSUE TITLE
Configuration files still don't work in 0.6.0 beta 2

### ISSUE THREAD

**Issue by sko4in** [screemerpl/cbleemsync#121]
Hi! I searched up this issue here and seems like I am not the first one with this question. In game emulator menu when I save changes to per-game config and then reload the game - all settings go back to default, even for games on USB drive. Could you please tell us (or provide a link to) what exactly is to be done to make it work?
Thanks!

**Comment by screemerpl** [comment]
Its an unfinished code in pcsx done by Sony ..to fix it ...download source code ...fix their code ... I will try to fix that for 0.7

**Comment by sko4in** [comment]
Thanks for your reply!
May I ask you this: as far as I understand - you do not use sony's built-in emulator anymore, even for pre-loaded games, right? I tried different settings and plug-ins, but I still see non square pixels which results in pixel shimmering. It does not affect any 3d games, but platformers like Castlevania Chronicles are almost unplayable, the whole screen looks like it's breathing. 
I installed retroarch with retrobleem, but it's the same story here too! I tried all possible aspect ratios in RA and I still see shimmering. I can fix it with some shaders but then I loose this crisp pixel perfect image.
I looked in the .cfg file and there are some settings like g_scaler3, g_..._width, g_..._hight and so on. Are those parameters being used by the emulator? Could you please post parameters description? I could not find it anywhere. Thanks so much for all your work!

**Comment by 101matrix101** [comment]
Hello sko4in,
Until the final solution in 0.7 version there is a way to save your settings.
Firstly load any game. Enter in the hidden menu by pressing select+triangle.
Make any changes you wish and then save it as global configuration.
Power off console unplug your usb drive and plug it to your pc.
In the games folder find the game you have save before the global configuration. Then delete completely the file pcsx.cfg. One click back and enter to !SaveStates folder. Find the same game folder. You will find a file pcsx.cfg inside. This is the global pcsx.cfg you have save before. Copy it and then go back again to the games folder and paste it in the game folder you have delete it before. Done.
If you wish you can paste the same pcsx.cfg in every game folder for the same settings.
Now your saved configuration will remain the same and the settings will be saved.
Also if you add more games you can paste the same pcsx.cfg in every new game folder for the same settings. Hope this helps a bit.

**Comment by screemerpl** [comment]
Its already in 0.7 code  ... closing
