### ISSUE TITLE
More detail about building autobleem

### ISSUE THREAD

**Issue by JGH-GOU** [screemerpl/cbleemsync#122]
Hi, thanks for your nice project.
What version of SDL2 did you use in this project? Could you tell me more detail about building autobleem? I want to build it from source code by myself. Thanks a lot.

**Comment by screemerpl** [comment]
Join our discord channel ...but in general it uses the same sdl2 as on the console 2.0.4, you also need sdl2 image mixer and ttf. As we link dynamically you just need headers and so libs for compile time
