### ISSUE TITLE
Savestates compatibility

### ISSUE THREAD

**Issue by pascl** [screemerpl/cbleemsync#136]
I don't know if this was expected, but savestates from bleemsync can be used as is in autobleem.

At the opposite, you can't use AB savestates as is in BS.

I switched several times between the 2 mods and spent some time on that. It seems that the folder written in "filename.txt.res" on the first line is not used in AB, but it is used in BS (and the folder is constant in BS: /data/AppData/sony/title/ followed by the filename).

Editing this file is enough to run the savestate in BS.
(and removing indexes in filenames to choose the right one as there is only one in BS so far).

But if it is not used, why AB doesn't write the same folder as BS in this file (to have full compatibility without user-edit) ? I don't go too far in the source, but there are copies to add indexes in filenames, the first line could be edited at this moment... ?

**Comment by screemerpl** [comment]
We never intended to be compatible with BS. AB uses extended functionality in PCSX emulator we added to store multiple savestates and run multi disc games from EvolutionUI as they should. Those features are not available in BS, so this is the reason AB has got more files in the ss folder. It's not a bug.
