### ISSUE TITLE
Created Danish translations

### ISSUE THREAD

**Issue by StepJefli** [screemerpl/cbleemsync#152]
I took the liberty of creating a Danish language file.
Use it if you want :)

[Danish.txt](https://github.com/screemerpl/cbleemsync/files/3285751/Danish.txt)

**Comment by ChocoNutDancer** [comment]
this is the latest English.txt containing all the strings that are translated.  
[English.txt](https://github.com/screemerpl/cbleemsync/files/3287703/English.txt)

**Comment by ChocoNutDancer** [comment]
lang tranlations updates are here. test 4. https://drive.google.com/drive/folders/16hXCn2FMLrK6-EJOOX_UoaluCsaE-9uK

**Comment by StepJefli** [comment]
Updated language file
[Danish.txt](https://github.com/screemerpl/cbleemsync/files/3289418/Danish.txt)

I can only read from the Google Drive folder

**Comment by screemerpl** [comment]
@StepJefli  ... Its already in Beta3 :) Thank you for contribution. Can you please join our discord for future updates. I am going to close this task
