### ISSUE TITLE
Italian Translation created

### ISSUE THREAD

**Issue by Crimaldi** [screemerpl/cbleemsync#158]
Ciao !
i've translated the strings file to Italian, it would be nice to include this into next updates
thank you,
Alex

[Italian.txt](https://github.com/screemerpl/cbleemsync/files/3312279/Italian.txt)

Edit: i was testing my translation and I will update/fix it during next day...

**Comment by ChocoNutDancer** [comment]
Text in the code has changed since the last release.  here is the latest english that need to be translated and the difference log file.
[English.txt](https://github.com/screemerpl/cbleemsync/files/3312634/English.txt)
[Italian_diff.log](https://github.com/screemerpl/cbleemsync/files/3312635/Italian_diff.log)

**Comment by Crimaldi** [comment]
here you are new Italian.txt file
i've completed this morning, thus i have not tested yet on console.

[Italian.txt](https://github.com/screemerpl/cbleemsync/files/3313693/Italian.txt)

**Comment by ChocoNutDancer** [comment]
it needs the english line followed by the translated line.  otherwise the code has no idea what the translated line is for.  I'll upload the spanish one so you can see.
[Spanish.txt](https://github.com/screemerpl/cbleemsync/files/3314582/Spanish.txt)

**Comment by Crimaldi** [comment]
I see, I'll fix it in a few minutes

**Comment by Crimaldi** [comment]
here you are!
[Italian.txt](https://github.com/screemerpl/cbleemsync/files/3314647/Italian.txt)
Right syntax?

**Comment by ChocoNutDancer** [comment]
I got rid of the two blanks lines.  and added a space at the end of Sorting:.  I didn't realize there was a space at the end.  I will fix that in the code and update all the lang files to match.  here is the modified txt file.  Thank you for your work!!  
[Italian.txt](https://github.com/screemerpl/cbleemsync/files/3314741/Italian.txt)

**Comment by Crimaldi** [comment]
great job!
i will test this last version tonight
if you need other info/translation to/from italian just ask me!! :)
Ciao

**Comment by Crimaldi** [comment]
there are some issue with that txt... some text show, but in english:
- the whole about page in in english
- "Players:" in game details (instead of "Giocatori:"
these strings are translated in txt file, but not loaded?

there are other text that are too long/could be enhanced/should be fixed (e.g - words containing an accent...)

**Comment by ChocoNutDancer** [comment]
you probably need the latest autobleem-gui that hasn't been released yet.
send me an email steve@iterator.com

**Comment by Crimaldi** [comment]
sent now

**Comment by Crimaldi** [comment]
Latest version,
some typo fixed
removed all accented letters (**é** is now **e'**)
[Italian.txt](https://github.com/screemerpl/cbleemsync/files/3317310/Italian.txt)

**Comment by screemerpl** [comment]
@Crimaldi any chance you are on our Discord for future Italian updates and contact with you ? ... I want to close this issue as your Italian translation  is already a part of Beta3
