### ISSUE TITLE
Games not showing up after update

### ISSUE THREAD

**Issue by Drake008** [screemerpl/cbleemsync#197]
I don't knmow if that is a problem but. After I updated I opnly have the 20 normal games in my list not the other ones I put on the stick. Can someone help me out?

**Comment by ChocoNutDancer** [comment]
Did a re-scan (press X on the startup screen) fix the problem?

**Comment by Drake008** [comment]
Well it found the games but they are not showing up.

**Comment by ChocoNutDancer** [comment]
try deleting your system folder and then re-scan.

**Comment by Drake008** [comment]
Tried it but it still won't work

**Comment by ChocoNutDancer** [comment]
suggestion from a beta tester: I would try deleting everything but the Games folder and re install AutoBleem B3

**Comment by screemerpl** [comment]
The games format may not be correct ... did it work before ?

**Comment by Drake008** [comment]
Well I deleted all except the games folder and copied the new AUtobleem onto the stick.
Yes all the games were showing up in the list.

It is strange but when I rescan he findes the 80 game si copied onto it and shows after the scanning that there are 80 games games. When I start autobleem they are nowhere to be seen.

**Comment by Drake008** [comment]
So no help here? I mean we did all we could do, i think or is there another way?

**Comment by ChocoNutDancer** [comment]
If you deleted everything but the games dir and reinstalled Beta 3 a re-scan should find all the games.  With no way to duplicate the problem it's hard to track it down.  Youre games are each in there own directory under /Games right?  Could you pick a game directory under /Games and upload a zip of it to google docs?  I could add that to my Games folder and do a re-scan.

**Comment by xwookieslayerx** [comment]
So I am also having the same issue. It was working for me without any problems. My games are bin/cue files. I first encountered this problem when I was having issues when I started having issues with my DS4 and 8bit duo connection. It connected fine and I was able to use the analog stick without mapping the controller (oddly); but then there was a mouse icon. After I held the up key and the share key(select) per a post I found. the fix got rid of the mouse icon but it crashed my system. after the reboot my controller was not working and after an hour of rebooting and trying different fixes I gave up and now Im stuck using the standard controller. 

Now when I attempt to load the games only the original games pop up. I have uninstalled then immediately reinstalled the autobleem software on the flash drive several times minus the games folder and it did not work. I then deleted the psx files and the configuration file and it also did not work. I then tried removing the game and re adding the game but it failed. the games come up on retroarch and work. I have a couple more Ideas to try but I am running out. hopefully someone can find a fix as i am close to just giving up and just use bleemsync as I really do not want to.

**Comment by ChocoNutDancer** [comment]
when you reloaded autobleem without any games did autobleem boot up or did it boot the original PSC software instead?

**Comment by xwookieslayerx** [comment]
I have not tried yet. I will try it when I get home  later today. I will also try a new drive as well and see if that works

**Comment by xwookieslayerx** [comment]
So I am able to get it to work now. here is what I tried. I first attempted to use a new flash drive. do note that I have the bleemsync for OTG support installed on my PSC. the flash drive I used was a 4GB kingston model. It would not even launch. So I went back to my original flash drive which is a 128GB sandisk glide and I noticed that the game configuration file was corrupted on all 100 games except 1. The games still work under retroarch. The one game that I could edit the game configuration file; per an older post of someone having this issue on a older version of autobleem. He changed anything that had a number equal to 1. To a 0 and that fixed the problem for that user. I tried it and it did not work. I then Removed the autobleem software and 1 game from the games folder, re added autobleem and then re added the removed game and it still failed. I then removed autobleem and retroarch as well as 1 game as a test but it still failed.

The final thing that I did to get it to work was to re format my drive. do note that it was formatted to fat32 previously. This time however I formatted it to exfat. I then added the autobleem software only and one game it the game showed up. I cant really figure out what caused it to begin with; but I hope this helps any other users who will use this software. hopefully someone can figure out why this is happening as it has happened before on previous versions of autobleem.

**Comment by ChocoNutDancer** [comment]
I wonder if the reason it worked was that you reformatted the drive not that it was reformatted to exfat.  perhaps the filesystem got corrupted on the drive and the reformat started with a fresh filesystem.

**Comment by bsawyers23** [comment]
What fixed this for me was to delete all the game.ini files then after rescan they were back

**Comment by ChocoNutDancer** [comment]
@bsawyers23 Any chance you have a copy of a game.ini from before?  I would love to know what in the game.ini file was causing the game to not show up.

**Comment by ChocoNutDancer** [comment]
actually I'd need the entire contents of a single game directory to track down why that happened.

**Comment by bsawyers23** [comment]
I think I do have a back up copy of the drive I’ll look when I get off work and post

**Comment by patrickvogt** [comment]
I had the same issue when updating to 0.7.1. It seems that Autobleem created 0 bytes (overwritten the existing) game.ini files which were (after the scan) not overwriteable neither by Autobleem nor by Windows. Only thing which helped was to check and repair the stick via Windows which automatically deleted the 0 byte game.ini files and another scan brought the games back in the menu. Without that the scan always told me "found XX games" but when I clicked on START, it just showed me the 20 stock games

I went back to 0.6.b2 then

**Comment by ChocoNutDancer** [comment]
Thank you Patrick.  That is a good clue.

**Comment by Drake008** [comment]
Well I deleted the game.ini files from the folders and now it finds 0 NEW games

**Comment by ChocoNutDancer** [comment]
@Drake008 is that after doing a re-scan?  the scan is what builds a missing game.ini.

**Comment by ChocoNutDancer** [comment]
@Drake008 is that after doing a re-scan?  the scan is what builds a missing game.ini.

**Comment by Drake008** [comment]
Yes thats after a rescan

**Comment by Drake008** [comment]
https://drive.google.com/open?id=1zAnEz9gEdih7PxZkTVKT6v-hU0oz1WvI

This the way to THPS2 like it is in my games folder whgich gets not "verified" or shown in the games list

**Comment by Drake008** [comment]
I deleted all the games and copied them back on the stick. Now he scans and updates the regional.db (which he did not do) and the games show up again.

Strange

**Comment by ChocoNutDancer** [comment]
I tried your game dir and it worked fine for me.  I wish I knew what is causing this as multiple people have reported seeing games not appearing.  
![image](https://user-images.githubusercontent.com/12785165/63261055-8705fe80-c250-11e9-8e24-7b8294ebce68.png)
