### ISSUE TITLE
read new games and game like Final Fantasy VII

### ISSUE THREAD

**Issue by Metro-City** [screemerpl/cbleemsync#223]
Hi everyone, I wanted to ask for help with games with multiple disks, I use .PBP files, when I press scan games in the main menu I see the game as a single disk, how can I solve it? Thank you

**Comment by screemerpl** [comment]
This is how the PCSX emulator does it ... Solutions: Do not use PBP (cue/bin have no problem like that) or split multidisk PBP to "one file per disk" using PSX2PSP
