### ISSUE TITLE
custom PCSX version 

### ISSUE THREAD

**Issue by screemerpl** [screemerpl/cbleemsync#23]

**Comment by lambtor** [comment]
What would be the best way to modify the boot script to skip the autobleem menu, so it boots directly into the carousel UI and games run with the updated build of pcsx_rearmed?  I'm looking to completely ignore retroarch and separate retroarch/bleemsync by using different USB sticks.

**Comment by screemerpl** [comment]
Custom PCSX is now updated with new functions support like widescreen and filter switch
