### ISSUE TITLE
NTFS Filesystem support (partial)

### ISSUE THREAD

**Issue by alucard73** [screemerpl/cbleemsync#24]
the version bleemsync 1.0 is out but I do not like at all to install the games which is absolutely not practical. Since they put the possibility to put the usb in exfat and ntfs, would it be possible that you integrate this compatibility? I tried but it supports only the fat32, if I try in exfat I have a mistake 001-001.

**Comment by screemerpl** [comment]
I havent do any reserach yet but this is another good idea to consider but only if i find safe solution (without change internal memory)

**Comment by alucard73** [comment]
I think that it is not possible without modifying the Nand, it would be necessary to be able to make a backup of this nand if the user wishes it and to be able to reinject it if there is a problem

**Comment by alucard73** [comment]
Hello
do you think it would be possible to put several USB sticks with a HUB and so have more games in the carousel with bleemsync?

**Comment by screemerpl** [comment]
I am sure ... NOT ... playstation classic mounts the sticks to /media folder internally so only one media can be mounted... this would also need to change emmc (/etc/fstab probably).

**Comment by screemerpl** [comment]
Ok - I did some research with nex(the person who helps with testing etc.) - We can probably add NTFS in safe way but with small workaround....two partitions on USB - first one with FAT32 (about 5MB part size only) that will boot and inject NTFS, the rest of the USB will be NTFS, but this will be for "power users" only.

**Comment by alucard73** [comment]
Good news
Thanks

**Comment by alucard73** [comment]
OK, thanks
in the meantime I would use the bleemsync 1.0 NTFS until you find another solution. I tried the exfat but this one does not work create the update.db so I did not try the NTSF believing that it would not work.

As far as retroarch is concerned, do you think it's possible to launch the carousel games directly with the libreto core pcsx rearmed because some games work pretty badly?
In any case you are doing a good job and you are listening to us to improve the program

**Comment by screemerpl** [comment]
Closing as no point to play in with two separate partitions ... safe way to install payload is better.
