### ISSUE TITLE
Feature Request: Filter PS1 games by Genre

### ISSUE THREAD

**Issue by zeusz4u** [screemerpl/cbleemsync#246]
I would like to request a feature for filtering games by genre: a filter to show only "Action", or "RPG", "FPS" games for PS1 games (in addition to the currently available "Internal/USB/Favorites").

This would help a lot to actually choose what to play with huge PSX games collections.

I think with all the metadata already available for PS games (currently shown in Autobleem: Serial, Region, No-Players, Year) it should definitely be possible to tag games by genre, and even filter them.

**Comment by ChocoNutDancer** [comment]
the next release will have the ability to organize your games in folders and sub folders.  for example /Games/Sports/Soccer

**Comment by zeusz4u** [comment]
> the next release will have the ability to organize your games in folders and sub folders. for example /Games/Sports/Soccer

Can this be made automatically based on metadata available for the title or will it be a manual process? You can at this point organize your titles into playlists in retroboot I think. I'm looking for Autobleem to do it for me if possible :).

**Comment by ChocoNutDancer** [comment]
When you create the USB stick on your PC, drag and drop the games to whatever folder you want.

**Comment by zeusz4u** [comment]
Doesn't the included CoverDB already contain such metadata for each game ID?

https://psxdatacenter.com/games/P/K/SLES-02899.html

Don't get me wrong, I see the advantages of also organizing them manually, but the genre metadata should already be readily available, just a filtering option is needed in the GUI, and possibly display the info on the game page... I would most likely want to see the game description as well, since many games I don't even know about - like the Genesis Mini does show you game descriptions of every game included. Not sure if this is possible though, since this would probably increase the DB size by a lot, but simple ASCII text also compresses fairly well (by 90%).

**Comment by zeusz4u** [comment]
Unfortunately I don't have any experience with GUI development to fork it and start working on it on my own as I'm a poor C++ backend dev :(

**Comment by ChocoNutDancer** [comment]
the cover is just a picture

**Comment by zeusz4u** [comment]
Yeah it is, but it's in a BD file, along with other meta data info like the identifier (SLES-XXXX/SLUS-XXX whatever their code is, probably other data such as number of players, year of release etc), this is how titles are identified and covers assigned for a game in Autobleem. Other wise it would have been manual work and you would start with blank covers :).

**Comment by ChocoNutDancer** [comment]
the SLES etc is the game ID only.  there is no meta data.  even if there was I wouldn't use it.  I wouldn't organize it based on a person at sony deciding what genre it belongs in.  is it "puzzle" or is it "kids"?  is it "action" or is it "fighting".  AB sub dir feature is implemented so that you decide the category.  further discussion on this is pointless.  there is no meta data.  the sub dir feature is already implemented, it works, and that is the way it works.
