### ISSUE TITLE
Initial GUI keeps appearing after reboot

### ISSUE THREAD

**Issue by andyderuyter** [screemerpl/cbleemsync#3]
The initial GUI (where it asks to do an initial scan wit 'X') keeps appearing. What data do you need to investigate?

The thing is, when I first tried it with only a few games, it worked as intended after reboot. So I got the screen after reboot where it provided some options to scan, load original games etc.

Log files included.

[autobleem.log](https://github.com/screemerpl/cbleemsync/files/2703826/autobleem.log)
[ui_menu.log](https://github.com/screemerpl/cbleemsync/files/2703827/ui_menu.log)
[error.log](https://github.com/screemerpl/cbleemsync/files/2703839/error.log)

**Comment by screemerpl** [comment]
Look into out.txt in your /media/cbleemsync.. inside this log file you see all game scanning result. Looks like one of your games is forcing rescan, this happens in 99% of the time when cue file points to non existing bin files (look for FAIL text in file and find a game name ABOVE it). Remove the game of fix the cue file. I am going to create some code to prevent this in next release (probably by removing broken cue file and generating it again)
