### ISSUE TITLE
memory card bug

### ISSUE THREAD

**Issue by alucard73** [screemerpl/cbleemsync#39]
Here I just tested for arc the lad, I have my arc backup the lad 1 on the arc memory card the lad 2. When I make Shared Arc the Lad 1 to share my data of what I have on Arc the Lad 2 he's creating me empty memory card. I made several methods and still empty, I checked with a memory card editor and it is indeed empty.

Why not do instead of Shared, copy the memory card and then arc the lad 1 to change MC?

Holy job that you did with this version

**Comment by screemerpl** [comment]
it just work like this ... you have your save of ark1 ... you share first... then open ark2 and select the mem card from repo. Believe me it works ...Sony UI does not show custom data as it has no access to autobleem, but you can see the card was changed in PCSX hidden menu when you start the game... until the game starts sonyui will not see mapped cards

**Comment by screemerpl** [comment]
Sorry mate - you are right its a bug... I am now working on the hotfix.

**Comment by alucard73** [comment]
thank you very much for being attentive. I had use a pc program to check the memory card ;)

**Comment by screemerpl** [comment]
Ok I just updated the release package with the fix - the share memory card option was not transferring card data. After you re-download it should work. Just replace AutoBleem folder and put back cover databases. I am closing this issue.
