### ISSUE TITLE
Final Fantasy VII cover not found?

### ISSUE THREAD

**Issue by andyderuyter** [screemerpl/cbleemsync#4]
It just gives me the yellow default cover. 

This is the Game.ini content it generated:

    [Game]
    Discs=Final Fantasy VII (USA) (Disc 1),Final Fantasy VII (USA) (Disc 2),Final Fantasy VII (USA) (Disc 3)
    Title=Final Fantasy VII (USA)
    Publisher=Other
    Players=1
    Year=2018
    Automation=1

**Comment by screemerpl** [comment]
Found the reason. It will be fixed in next release.

**Comment by screemerpl** [comment]
Fixed in 0.3
