### ISSUE TITLE
Reboot console/return to Autobleem UI with button combination

### ISSUE THREAD

**Issue by nex86** [screemerpl/cbleemsync#47]
Have the ability to comfortably restart the console or go back to the Autobleem UI with a button combination on the controller when you are in the Sony UI.
select+start+L1+L2+R1+R2 would be a good combination.

I'm not sure how hard this is going to be to implement but it will most likely require a seperate process or service to be running in the background.
killing sony processes and starting the Autobleem UI again would be quicker than an entire reboot,
but I don't know which would be safer.

**Comment by screemerpl** [comment]
EvoUI already has that
