### ISSUE TITLE
does everything is stored in the USB thumbs?

### ISSUE THREAD

**Issue by AX3L87** [screemerpl/cbleemsync#6]
Are everything not related to the original PSC emulator stored into the USB thumbs (ie. games status/virtual memory card)?

Or something can be present into the PSC's internal memory after use AutoBleem (0.3.1)?

Thanks

**Comment by screemerpl** [comment]
Autobleem does not change any file on the internal emmc storage, everything is stored on the USB. The only folder affected on root fs is /tmp that is a temporary ram disk. You can take your USB connect to any other PCS and play your games.
