### ISSUE TITLE
Add .DS_store to gitignore

### ISSUE THREAD

**Issue by ThaFridge** [screemerpl/cbleemsync#61]
See title, if you don't have the time for it. i can make a pull request in order to set up the gitignore properly

**Comment by mGGk-fr** [comment]
Hello,

The cleaning has been done on the develop branch.

As we use Git flow, cleaning will be done on master at next release.

**Comment by ThaFridge** [comment]
Perfect! don't like messy codes :P my brain can't handle that

**Comment by screemerpl** [comment]
I am closing this ... Not an issue in develop branch
