### ISSUE TITLE
Known issue: Some Micro-USB sticks will crash

### ISSUE THREAD

**Issue by ThaFridge** [screemerpl/cbleemsync#65]
Currently, we have encountered a bug/system failure with certain USB pen/thumb drives
that will prevent autobleem from completely booting

Problem:
Booting from USB2.0 -> boots autobleem 0.5 -> when RE/SCan -> PSC will reboot/black screen -> Loop continues 

Booting from USB2.0 -> Boots AutoBleem 0.5 -> Starting (Pressing O) Original -> Will boot Sony UI with original games and Secret menu 

We have found the problem, by delaying certain stresses on the USB devices! Fix will be implemented rather soon! However we came to the conclusion that certain USB drives don't have the reading/write speed to keep up with AutoBleem. Terfor your experience using these stick will be very poor!

Example
with fix implementation, AutoBleem will boot properly. After entering the games library certain games “Like Tekken 3” will load really slow, when in game. the game will buffer from time to time. This will bring back the old “Tekken 3” feeling like it was on the original Playstation 1 however in 2019 we don't accept certain delays/frame/buffers any more ;)

**Comment by screemerpl** [comment]
Power Mod, OTG, Hub.... multiple fixes developed over time - closing
