### ISSUE TITLE
Black screen after hitting Start or Rescan?

### ISSUE THREAD

**Issue by vexe** [screemerpl/cbleemsync#68]
I have a SanDisk USB 3.0 FAT32 stick named SONY.

Got the zip contents (0.5) extracted into it with some games, db files copied into the bin/db folder

I plug it in while the system is off, turn the system on, the system flashes for a bit, I see autobleem menu, I hit Start or rescan or do anything, I just get a black screen. If I power off the system and power back up, I don't see autobleem ever again...

What am I doing wrong?

Thanks

**Comment by screemerpl** [comment]
Known issue
https://github.com/screemerpl/cbleemsync/issues/65
 - we are working to find out the reason already ... some people reported improvement when using just different type of USB sticks ...or downgrading to more stable release 0.4
