### ISSUE TITLE
Automate folder listing

### ISSUE THREAD

**Issue by mGGk-fr** [screemerpl/cbleemsync#73]
Let's have a folder called maybe "toInstall" at the root of the USB.
On boot, Autobleem will read the files of the folder and create corresponding folders in Games folder.
The question is : do we name folder by the file name or by the game serial ?

**Comment by screemerpl** [comment]
Duplicate of:
https://github.com/screemerpl/cbleemsync/issues/36 
Why to use separate folder - we can use Games itself and just scan for files, but I want to make it more scientific, so for example if it is cue it should go with all bins etc
