### ISSUE TITLE
Add support for wireless controllers

### ISSUE THREAD

**Issue by nyclide** [screemerpl/cbleemsync#92]

**Comment by mattpelegrin** [comment]
Any idea how to get an 8bitdo to read in Autobleem when paired with a PS3 controller? Receiver and controller are paired up but when I plug into the PSC Autobleem doesn't recognize that a controller is plugged in and asks me to plug one in even though the 8bitdo is already in.

**Comment by screemerpl** [comment]
Controller support added in 0.6.0b3
