### ISSUE TITLE
PBP files do not work correctly, 

### ISSUE THREAD

**Issue by Jamieasy** [screemerpl/cbleemsync#93]
I'm not exactly sure what the issue is but most PBP s come with two to three other files usually a Key.bin and a dat file? , which of these files are actually required and which one of these files need to be , renamed?, Half of my PBP files are named eboot.pbp what gives?

**Comment by screemerpl** [comment]
Adding here problem changing discs in pbp by pcsx ... More investigation needed for a fix

**Comment by molnara** [comment]
Those files are for encrypted pbp's, which arn't supported.  You need to create your own unencrypted pbp's using PSX2PSP.

**Comment by screemerpl** [comment]
closing as not constructive - clearly stated in the documentation about this
