### ISSUE TITLE
USB stick formerly detected by PSC, not detected anymore after a hard reboot.

### ISSUE THREAD

**Issue by Nosferatumiamor** [screemerpl/cbleemsync#97]
Hello, this problem happened to me with a few usb sticks now. I had bought a stick known for it's compatibility with the psc and everything was working just fine (had still a hundred of games working nicely a few hours ago) until I was forced to do a hard reboot on my console due to a freeze in a game (reset and power button would just do nothing).
Since then I've been unabled to boot autobleem with this stick. I formatted it, re-installed everything ... but it just won't do the trick, PSC doesn't boot autobleem anymore. 
The stick still works perfectly on my computer though, it's not broken or anything.

**Comment by dridder123** [comment]
What is the gigabyte size of your stick and second is it formatted to FAT32

**Comment by Nosferatumiamor** [comment]
64gb and yes it is formatted to FAT32, but don't worry, I formatted it once more and installed the latest version of autobleem, and now it works again ... I'm reinstalling my games right now, sorry for that. Don't really know why it took a few tries before going back to normal though.

**Comment by dridder123** [comment]
Awesome

**Comment by screemerpl** [comment]
I see you found it our yourself ... but ... there is no need to format ... after the hard reset a good slap with CHKDSK tool should repair all the problem without formatting ... PSC does not check the file system on boot so you can do it using Windows machine - look here https://www.tekrevue.com/tip/fix-hard-drives-chkdsk-windows-10/ ... similar thing on linux is to use fsck command

**Comment by Nosferatumiamor** [comment]
Thanks a lot, it happened a couple of times and each time I went through the whole "formatting and reinstalling everything" routine, glad to know it can be avoided easily.

**Comment by skamanny** [comment]
I'm having the same problem I bought another stick but still nothing followed all the same steps as before but nothing please help
