### ISSUE TITLE
Spyro 2, Spyro 3 & T'ai Fu - Wrath of the Tiger Games not working properly

### ISSUE THREAD

**Issue by Hitmanreborn05** [screemerpl/cbleemsync#98]
Every game i have tested/played for so far works really well except for the following ones:

Spyro 2 Ripto's Rage:
Cutscene Sound is buggy & Entering another world not the first lvl, the Game just crashes.

Spyro 3 Year of the Dragon:
The Loading Screen is going from small to big rapidly.

T'ai Fu - Wrath of the Tiger: The Game can be started but if you want to load the first lvl the loading screen is standing still with no progress of the loding bar.

Will there be an update & fix in the furture for those issues?

Thanks in advance for any information or help.

**Comment by screemerpl** [comment]
Hi I am afraid this is more to do with PCSX ReARMed (emulation engine that runs your Playstation Classic) than Autobleem itself...but we can have a look if something can be done for those games

**Comment by nex86** [comment]
I had the same issue with the PAL version of Spyro 3. but NTSC is fine.
But as Screemer said, its a problem with PCSX, not Autobleem.
